### ISSUE TITLE
no close when press X from window

### ISSUE THREAD

**Issue by wifislax-ng** [aarnt/qtgzmanager#2] opened 2021-02-07 22:01 UTC
Hi , when i press in the X button window , the app , remains under notification area.
I chek the setup , and that option is disabled on the config , but he goes hidden on notification area.

**Comment by aarnt** [comment] 2021-02-08 13:53
Hi @wifislax-ng 

I could not reproduce this error here.

**Comment by wifislax-ng** [comment] 2021-02-08 22:08
I build again a make new test , im not sure if the other issue can affect , cause probably , if actions "pending" , app , not close , and go notification area waiting end actions from user.

I go download and build new to test , THANKS!

**Comment by wifislax-ng** [comment] 2021-02-08 22:42
Hello , i make new package and test , this issue persist.
I see when i open the app , he is goes directly on systray with icon .. apps open good, but the windows is not opened like other apps , not on taskbar, he is goes directly to sytray notification area.

When clik to close on the right up window X button , window is go to notification but remains opened , only way to close right click on the icon on systray and select exit.

There is a interesting info

1 - root acount
2 - plasma desktop
3 - current up-to-date version 64 bits

The issue is here when launched from menu , using the provided .desktop and when i launch from konsole , same result.
The setup , is not touched , i open the config file and see hidden on close is = 0 , Disabled.
I try deleting config to force a new one with defaults ... nothing fix.

The more extrange here is why put directly an notification icon , instead a regular task , on taskbar.

**Comment by aarnt** [comment] 2022-03-18 22:27
Fixed in upstream code.

**Closed as completed by aarnt** 2022-03-18 22:27 UTC
